# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af9f018f1fdccd4eb153182f181737d4120e533b0c1ae5fe31fe13b049f50be18afd29e4cf8ba5dad1e6355eb983ec086ebca61310316095c1d7d3617397e835

test:
  secret_key_base: 8e0af9d25b0da57e7dde66c4de7ba5da3732d0202a2ba0e0d09d8945a48ccb63ac36f7bc1c32c5c12e782be5e2c91c669571b0f0a46ddc25a92586004b8fdd7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
